const artStyles=document.createElement('link');artStyles.rel='stylesheet';artStyles.href='../../game-art.css';document.head.appendChild(artStyles);const $=id=>document.getElementById(id);let mode=null,round=0,stars=0,locked=false;
function tone(ok){const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=ok?720:230;g.gain.setValueAtTime(.1,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.25);o.start();o.stop(c.currentTime+.25)}
function buildMenu(){const menu=$('game-menu');menu.innerHTML='';GAME_CONFIG.games.forEach((game,i)=>{const b=document.createElement('button');b.className='game-card';b.style.setProperty('--bg',game.color);b.style.setProperty('--shadow',game.shadow);b.innerHTML=`<img class="game-art" src="${game.image}" alt="${game.title} game illustration"><strong>${game.title}</strong><small>${game.hint}</small>`;b.onclick=()=>startGame(i);menu.appendChild(b)})}
function startGame(i){mode=i;round=0;stars=0;$('stars').textContent=0;$('menu-screen').hidden=true;$('finish').hidden=true;$('play-screen').hidden=false;showRound()}
function showRound(){locked=false;const game=GAME_CONFIG.games[mode],r=game.rounds[round];$('mode-label').textContent=`${game.icon} ${game.title} • ${round+1}/${game.rounds.length}`;$('prompt').textContent=r.prompt;$('scene').innerHTML=r.scene;$('message').textContent='';$('next').hidden=true;const answers=$('answers');answers.innerHTML='';r.answers.forEach((a,i)=>{const b=document.createElement('button');b.className='answer';b.innerHTML=`<span class="answer-pic">${a.pic||''}</span><span class="answer-label">${a.label}</span>`;b.onclick=()=>pick(i,b);answers.appendChild(b)})}
function pick(i,b){if(locked)return;const r=GAME_CONFIG.games[mode].rounds[round];if(i===r.correct){locked=true;stars++;$('stars').textContent=stars;b.classList.add('correct');$('message').textContent=GAME_CONFIG.good[Math.floor(Math.random()*GAME_CONFIG.good.length)];tone(true);$('next').hidden=false}else{$('message').textContent=GAME_CONFIG.tryAgain;tone(false);b.animate([{transform:'rotate(-2deg)'},{transform:'rotate(2deg)'},{transform:'none'}],{duration:260})}}
function nextRound(){const game=GAME_CONFIG.games[mode];if(++round<game.rounds.length)showRound();else{$('play-screen').hidden=true;$('finish').hidden=false;$('final-stars').textContent=stars;$('finish-title').textContent=`You finished ${game.title}!`}}
function showMenu(){$('play-screen').hidden=true;$('finish').hidden=true;$('menu-screen').hidden=false}
$('next').onclick=nextRound;$('menu-from-play').onclick=showMenu;$('menu-from-finish').onclick=showMenu;$('again').onclick=()=>startGame(mode);$('suite-title').textContent=GAME_CONFIG.title;$('subtitle').textContent=GAME_CONFIG.subtitle;buildMenu();
